server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: bruce

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
app:
  jwt:
    secret: myMonolithSecretKeyThatShouldBeExternalizedInMicroservices2024FoodDelivery!
    expiration-ms: 86400000
